SecondTask/randomname/urls.py
from django.conf.urls import url

from randomname import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^member_api$', views.members, name='member_api'),
]

SecondTask/system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from system import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^random/', include('randomname.urls', namespace='randomname')),
]

SecondTask/randomname/models.py
from django.db import models

# Create your models here.


class Member(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'members'

SecondTask/randomname/forms.py
from django import forms

from .models import Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('name',)

SecondTask/randomname/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from .models import Member


def index(request):
    return render(request, 'randomname/members.html')


class MembersView(View):
    """Simple API class for model Members
    
    """
    queryset = Member.objects.all()

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(MembersView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """Performs GET request processing for Member model.
        Args:
            request: Django request object
            *args: list positional arguments
            **kwargs: dictionary keyword arguments

        Returns:
            Http response object
        """
        winners = [member.name for member in self.queryset.order_by('?')[:3]]
        return JsonResponse({'winners': winners}, safe=False)

    def post(self, request, *args, **kwargs):
        data = json.loads(request.body.decode('utf-8'))
        name = data['name']
        try:
            Member.objects.get(name=name)
            message = "Member is exists"
        except:
            Member.objects.create(name=name)
            message = "Member was created"

        return JsonResponse({'message': message}, safe=False)

    def delete(self , request, *args, **kwargs):
        body = json.loads(request.body.decode('utf-8'))
        name = body['name']
        try:
            Member.objects.get(name=name).delete()
            message = "Member was deleted"
        except:
            message = "Member was not deleted"
        return JsonResponse({'message': message}, safe=False)


members = MembersView.as_view()

SecondTask/system/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

SecondTask/randomname/templates/randomname/members.html
{% extends 'index.html' %}

{% block content %}

    <button onclick="getWinners()"> Получить победителей</button>
    <h3>Список победителей</h3>
    <ul class="winners_list"></ul>
    <label for="add_delete_member">Введите имя участника</label>
    <input id="add_delete_member"/>
    <button onclick="addMember()"> Добавить участника</button>
    <button onclick="deleteMember()"> Удалить участника</button>
{% endblock content %}

{% block extrajs %}
    <script>
        $(document).ready(function () {
            getWinners();
        });
        function getWinners() {
            var winners_list = $('.winners_list');
            winners_list.empty();
            $.ajax({
                url: '{% url 'randomname:member_api' %}',
                type: 'GET',
                success: function (response) {

                    response['winners'].forEach(function (value, i) {
                        winners_list.append('<li>'+value+'</li>');
                    })
                }
            })
        }
        function deleteMember() {
            var name = $('#add_delete_member').val();
            $.ajax({
                url: '{% url 'randomname:member_api' %}',
                type: 'DELETE',
                data: JSON.stringify({
                    'name' : name
                }),
                success: function (response) {
                    alert(response['message'])
                }
            })
        }
        function addMember() {
            var name = $('#add_delete_member').val();
            $.ajax({
                url: '{% url 'randomname:member_api' %}',
                type: 'POST',
                data: JSON.stringify({
                    'name' : name
                }),
                contentType: "application/json; charset=utf-8",
                dataType:"json",
                success: function (response) {
                    alert(response['message'])
                }
            })
        }
    </script>
{% endblock extrajs %}

SecondTask/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--jQuery 2.2.3-->
    <script src="{% static 'jquery-2.2.3.min.js'%}" type="text/javascript"></script>
</head>
<body>
    <h1>Test project</h1>
    {% block content %}
        <b>Viacheslav Kochergin</b>
        <p><a href="{% url 'randomname:index' %}">Go to randomizer</a></p>
    {% endblock content %}
{% block extrajs %}

{% endblock extrajs %}
</body>
</html>